name = "cat-chat-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
# You will need to create a KV namespace and put the ID here.
# Run: wrangler kv:namespace create "SITES_STORE"
binding = "SITES_STORE"
id = "15f785eb95034afcae27fae56412ad0d"
